In [1]:
import pandas as pd

In [2]:
df_estoque = pd.read_csv("../dados/estoque_atual.csv", sep=",")
df_consumo = pd.read_csv("../dados/consumo_mensal.csv", sep=",")

In [3]:
display(df_consumo)

,Data,Codigo,Produto,Grupo,Setor,Quantidade_Consumida
0,2024-01-01,14,Furosemida 20mg,Medicamento,Urgencia,14
1,2024-01-01,20,Cateter Venoso 20G,Material Hospitalar,UTI,18
2,2024-01-01,4,Equipo Macrogotas,Material Hospitalar,Bloco Cirurgico,99
3,2024-01-01,10,Ceftriaxona 1g,Antibiotico,Urgencia,13
4,2024-01-01,23,Compressa Gaze,Material Hospitalar,Urgencia,105
...,...,...,...,...,...,...
2268,2024-06-30,7,Agulha 25x7,Material Hospitalar,UTI,86
2269,2024-06-30,23,Compressa Gaze,Material Hospitalar,Urgencia,75
2270,2024-06-30,13,Ondansetrona 4mg,Medicamento,UTI,22
2271,2024-06-30,22,Mascara Cirurgica,Material Hospitalar,Urgencia,82
2272,2024-06-30,6,Seringa 20mL,Material Hospitalar,Clínica Médica,93

In [4]:
display(df_estoque)

,Codigo,Produto,Grupo,Estoque_Atual,Estoque_Minimo,Estoque_Maximo,Tempo_Reposicao_Dias
0,1,Dipirona 500mg/mL,Medicamento,122,122,592,13
1,2,"Soro Fisiologico 0,9% 500mL",Solucoes,91,50,864,13
2,3,Soro Glicosado 5% 500mL,Solucoes,478,117,689,6
3,4,Equipo Macrogotas,Material Hospitalar,891,181,511,4
4,5,Seringa 10mL,Material Hospitalar,363,187,772,3
5,6,Seringa 20mL,Material Hospitalar,479,87,308,14
6,7,Agulha 25x7,Material Hospitalar,876,78,752,12
7,8,Luva Procedimento M,Material Hospitalar,495,44,433,17
8,9,Omeprazol 40mg,Medicamento,977,80,846,5
9,10,Ceftriaxona 1g,Antibiotico,504,80,926,11
10,11,Ampicilina 1g,Antibiotico,186,47,634,16
11,12,Metoclopramida 10mg,Medicamento,261,38,583,4
12,13,Ondansetrona 4mg,Medicamento,359,121,687,9
13,14,Furosemida 20mg,Medicamento,447,37,271,16
14,15,Hidrocortisona 100mg,Medicamento,100,193,954,10
15,16,Adrenalina 1mg/mL,Medicamento,407,31,620,12
16,17,"Atropina 0,25mg/mL",Medicamento,791,83,759,14
17,18,Cloreto de Sodio 20%,Solucoes,181,43,513,10
18,19,Glicose 50%,Solucoes,481,69,993,18
19,20,Cateter Venoso 20G,Material Hospitalar,768,111,363,15
20,21,Cateter Venoso 22G,Material Hospitalar,60,186,400,15
21,22,Mascara Cirurgica,Material Hospitalar,84,118,838,3
22,23,Compressa Gaze,Material Hospitalar,667,92,430,19
23,24,Esparadrapo,Material Hospitalar,411,192,810,3
24,25,Alcool 70%,Material Hospitalar,398,34,723,9